/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface FluidContainer {}
  interface FluidElement {
    'isAnimating': boolean;
    'show': boolean;
  }
}

declare global {


  interface HTMLFluidContainerElement extends Components.FluidContainer, HTMLStencilElement {}
  var HTMLFluidContainerElement: {
    prototype: HTMLFluidContainerElement;
    new (): HTMLFluidContainerElement;
  };

  interface HTMLFluidElementElement extends Components.FluidElement, HTMLStencilElement {}
  var HTMLFluidElementElement: {
    prototype: HTMLFluidElementElement;
    new (): HTMLFluidElementElement;
  };
  interface HTMLElementTagNameMap {
    'fluid-container': HTMLFluidContainerElement;
    'fluid-element': HTMLFluidElementElement;
  }
}

declare namespace LocalJSX {
  interface FluidContainer extends JSXBase.HTMLAttributes<HTMLFluidContainerElement> {}
  interface FluidElement extends JSXBase.HTMLAttributes<HTMLFluidElementElement> {
    'isAnimating'?: boolean;
    'show'?: boolean;
  }

  interface IntrinsicElements {
    'fluid-container': FluidContainer;
    'fluid-element': FluidElement;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


